### ISSUE TITLE
Missing `find_package(YCM REQUIRED)`

### ISSUE THREAD

**Issue by andrearosasco** [xEnVrE/thrift-cpp-python-interop#1]
I don't know if this is specific to how I've installed the superbuild but I had to add `find_package(YCM REQUIRED)` to the cpp-library CMakeLists to have it find the modules.

**Comment by xEnVrE** [comment]
It might be that I have tested everything using a `robotology-superbuild` environment with some differences w.r.t your installation.

Let's keep this open until we understand where the problem is.

**Comment by xEnVrE** [comment]
> I don't know if this is specific to how I've installed the superbuild but I had to add find_package(YCM REQUIRED) to the cpp-library CMakeLists to have it find the modules.

Can you please post the error you are getting if you don't add that `find_package`? Thanks

**Comment by andrearosasco** [comment]
Actually, it doesn't happen anymore. If I remember correctly it was something related to not finding AddInstallRPATHSupport.
Since it is present in the cmake directory of this repository I think I didn't have it in the correct path. 
I guess this can be closed
